PRODUCT_PRICE_MAPPING = [
    {
        "consumption_product_code": "EPM0F",
        "consumption_product_name": "Finished Motor Gasoline",
        "price_route": "gnd",
        "price_product_code": "EPM0",
        "is_active": True,
        "notes": "Weekly retail gasoline price, all grades combined.",
    },
    {
        "consumption_product_code": "EPD0",
        "consumption_product_name": "Distillate Fuel Oil",
        "price_route": "gnd",
        "price_product_code": "EPD2D",
        "is_active": True,
        "notes": "No.2 diesel chosen as it represents the bulk of distillate fuel oil volume.",
    },
    {
        "consumption_product_code": "EPJK",
        "consumption_product_name": "Kerosene-Type Jet Fuel",
        "price_route": "spt",
        "price_product_code": "EPJK",
        "is_active": True,
        "notes": "Exact code match confirmed via EIA facet endpoint.",
    },
    {
        "consumption_product_code": "EPLLPZ",
        "consumption_product_name": "Propane and Propylene",
        "price_route": "spt",
        "price_product_code": "EPLLPA",
        "is_active": True,
        "notes": "Closest available match; propylene is not separately priced by EIA.",
    },
    {
        "consumption_product_code": "EPP0",
        "consumption_product_name": "Total Petroleum Products",
        "price_route": None,
        "price_product_code": None,
        "is_active": False,
        "notes": "Aggregate category across all products; EIA does not publish a standalone price for it.",
    },
    {
        "consumption_product_code": "EPPO4",
        "consumption_product_name": "Other Oils",
        "price_route": None,
        "price_product_code": None,
        "is_active": False,
        "notes": "No matching price product code found in any checked EIA price route.",
    },
]