dev:
  catalog: dbr_dev_ua5816bd
  bronze_schema: roksolana_shendiu770_bronze
  silver_schema: roksolana_shendiu770_silver
  bronze_volumes_path: "/Volumes/dbr_dev_ua5816bd/roksolana_shendiu770/raw_files/"
  consumption:
    source_file: petroleum_raw.json
    source_table: petroleum_raw
    target_table: petroleum_consumption
  prices:
    source_file: petroleum_prices_raw.json
    source_table: petroleum_prices_raw
    target_table: petroleum_prices

prod:
  catalog: dbr_prod_ua5816bd
  bronze_schema: roksolana_shendiu770_bronze
  silver_schema: roksolana_shendiu770_silver
  bronze_volumes_path: "/Volumes/dbr_prod_ua5816bd/roksolana_shendiu770/raw_files/"
  consumption:
    source_file: petroleum_raw.json
    source_table: petroleum_raw
    target_table: petroleum_consumption
  prices:
    source_file: petroleum_prices_raw.json
    source_table: petroleum_prices_raw
    target_table: petroleum_prices